MiSTer-devel/NES_MiSTer

- NES.sv
- apu.sv
Use Images to write and read save files.
> Add save file support

- NES-lite.qsf
- NES.qsf
- NES.sv
- dpram.vhd
- mappers/mapLoopy.v
- mmu.v
- nes.v
FDS saving not currently supported.
Only tested with the PowerPak FDS BIOS.
Select pauses disk swap, just like the PowerPak mapper.
> Add support for Loopy's PowerPak mappers (24/26 [VRC6], 19[Namco106/163] and 20 [FDS])

- NES.sv
- video.sv
I added the PC-10 palette used for player's choice arcade games, and also other some popular ones from FirebrandX. He suggested to me that Smooth was a much more modern palette and more accurate than Unsaturated, so I switched that to the default palette for the core.
> Add PC-10 and additional palettes.

- apu.sv
The length counter was always using the faster envelope clock because
of a wrong if-else.
This made sounds play too short in some games like Flintstones title
music, Punch-out long falling sound and Zelda title music.
> APU: Fix square channel length counter

- NES.sv
- apu.sv
- video.sv
I fixed the square wave being off because of an off-by-one error and also the high pitched squeal from HDMI audio in some games (MegaMan 2) caused by the unfiltered triangle generating supersonic audio. I also added a few more popular palettes that people have been asking me for. They're more saturated for people who like a richer look. If I ever have to add more in the future, I will see if I can find a better way to deal with them.
> APU fixes and additional palettes

- NES.sv
- README.md
- cart.sv
- mappers/FDS.sv
- mappers/MMC1.sv
- mappers/MMC2.sv
- mappers/MMC3.sv
- mappers/MMC5.sv
- mappers/Namco.sv
- mappers/Sunsoft.sv
- mappers/VRC.sv
- mappers/generic.sv
- mappers/misc.sv
- nes.v
- ppu.sv
Further refactored mappers, cleaning up wires, ports, and correcting behavior of reset. In addition, mappers are now disabled when not selected, so that they do not create and maintain state incorrectly.
I also added a little documentation for each mapper to make testing and work easier.
Also:
-fixed power on/reset state of of PPU (thanks greyrogue) that caused some games (akamajou densestsu) to not load consistently.
-fixed PPU sync that was causing some NMI instability and causing some tests to fail. 
Now that most cleanup is done, the next thing I will do correct audio mixing in the cart mapper rather than at system level.
> Mapper Refactor - Phase 2

- NES.qsf
- NES.sv
- jt49_dcrm2.v
- mappers/FDS.sv
- mappers/MMC1.sv
- mappers/MMC2.sv
- mappers/MMC3.sv
- mappers/MMC5.sv
- mappers/Namco.sv
- mappers/Sunsoft.sv
- mappers/VRC.sv
- mappers/generic.sv
- mappers/misc.sv
- nes.v
- ppu.sv
Changes the following:
-Audio is now mixed in the mappers as it should be
-Corrected the polarity on audio
-Added a high pass filter from jt49. This fixes the extreme bias that was present in digital audio and corrects audio compatibility issues with Elgato capture carts and some tvs.
-Add a mute during reset to avoid loud "POP" when games start.
-Use signed audio out to double maximum volume
-Fix clock on MMC5 mapper. (Just Breed) so audio is now correct.
-Mix MMC5 at correct level
-Change amplification on VRC6 to be linear rather than logarithmic, as the original was
-Fix levels of VRC6 audio
-Rewrite Sunsoft 5B audio mapper, now correct sound in Gimmick!
-Adjusted VRC7 levels.
-Added a temporary fix for PPU "jitter" causing problems with scandoubler. I will fix this better when I …
> Mapper cleanup final phase

- NES.sv
- nes.v
- ppu.sv
- video.sv
These bits de-emphasize some or all of the colors. You can see them used when entering a battle in Final Fantasy 1 or pausing the game in Super Spy Hunter.
https://wiki.nesdev.com/w/index.php/Colour-emphasis_games
> enable color emphasis bits from PPU

- NES.sv
- nes.v
NES is a little harder than gameboy and genesis, since those two don't use backup ram for work space.
For NES I do this:
1) check iNES header for "has battery backed ram" flag
2) check prg ram 6000 - 7FFF or eeprom for writes
if both of these are true, save will be written exactly once next time OSD is opened, if the Autosave option is enabled.
This will get a lot of false positives in games like Adventure of Link or Final Fantasy where the prg ram is written all the time, however, it will still work to save the user's saves when the OSD opens. There might just be some extra writes that aren't needed. Since the OSD doesn't open that much, this still won't cause any appreciable wear to the SD card.
I enable the USER LED only when Autosave is on. It will stay on a lot in some games because …
> autosaving on OSD

- NES.sv
- apu.sv
- mappers/MMC5.sv
- mappers/Sunsoft.sv
- mappers/VRC.sv
- video.sv
Sorg: If you have time, please double check to make sure i'm not doing anything wrong in video changes. You have a lot more experience with this than me.
-Fix aspect ratio for NES. Although NES and SNES only draw 256 pixels, they pad the image to 280 pixels so that all of the visible pixels are inside the overscan. Therefor we scale to 4:3 from the correct resolution of 280x240. I adjusted the overscan calculation to match. I confirmed that now the image on a CRT and on HDMI matches exactly what you would see from a real NES.
-Fix frame timer in APU. It was causing a variety of notes to end early, audible in Ducktales, and probably many other things.
-Fix square/mix channel balance. The old LUT wasn't well balanced, this new one passes the APU_MIXER tests much better and matches the …
> fix audio and video

- NES.sv
- video.sv
- zapper.sv
-Target cursor now turns blue at edge of screen, to indicate you are shooting off the screen (some games require this)
-Target is now wider so games like Operation Wolf work better
-Mouse button and joystick button are trigger in both Mouse and Joystick mode now, to make mapping gun-like devices easier
> zapper tweaks

- mappers/MMC3.sv
Mapper 48 enable/disable registers are in reverse order compared to MMC3.
--Fixes Bubble Bobble 2 and Captain Saver.
There are still some slight graphical errors, likely related to irq timing, but I believe that requires better documentation of the hardware to fix.
> Fix Mapper 48 IRQs

- NES.sv
- apu.sv
- nes.v
- ppu.sv
AKA "I'm not your buddy, PAL"
PAL mode will be at the wrong speed (pitch in sound is off, etc) without a PLL reconfigure. The correct frequencies are: NTSC/Dendy: 21.477272, PAL: 21.2813696. Even though they seem close, the music pitch will be notably off unless those frequencies are used.
Otherwise, most PAL titles run correctly, including Elite. Some mappers were made without PAL in mind and will need to be looked at (Sunsoft 5b in particular).
edit: nevermind, gimmick works fine. I guess I fixed it in my last round of cleanups and tweaks.
> PAL and Dendy support.

- SOUND/OPLL/VM2413/envelopegenerator.vhd
- mappers/VRC.sv
It looks like the amplitude modulator phase was originally calculated as 4 bits (plus sign).  This was increased by 6 bits of precision, but the corresponding constants were not adjusted to match.
Improved mixing volumes by Kitrinx (with adjustment from James-F2).
> Fix VRC7 OPLL tremulo (Amplitude Modulator)

- NES.sv
- nes.v
- ppu.sv
- video.sv
correctly fixes the hsync issue. the CE counter in video.sv was getting out of aligment. Also reset at top level for more robust behavior.
> align video clock to system clock

- mappers/Sunsoft.sv
Cart RAM is mapped to high four address bits 1111.  Now that 2MB PRG sizes are allowed, this should be enforced in all mappers.
--Fixes Batman Return of the Joker
> Fix Sunsoft 5B (mapper 69) Cart RAM issue caused by 2MB PRG size change.

- ppu.sv
checking the 9th sprite as well resolves felix the cat and ninja gaiden, which takes care of all the overflow-to-mask situations documented on nesdev
> also check 9th sprite for repeats

- cart.sv
- mappers/FDS.sv
- mappers/JYCompany.sv
- mappers/MMC1.sv
- mappers/MMC2.sv
- mappers/MMC3.sv
- mappers/MMC5.sv
- mappers/Namco.sv
- mappers/Sachen.sv
- mappers/Sunsoft.sv
- mappers/VRC.sv
- mappers/generic.sv
- mappers/misc.sv
- nes.v
Mappers should set prg_bus_write high when data needs to be output
to the bus with register reads. The rest is open bus.
> Mappers: open bus by default

- NES.qsf
- NES.sv
- mappers/MMC3.sv
- mappers/VRC.sv
- mappers/misc.sv
- nes.v
- ppu.sv
Several timing related fixes. Passes 3 more tests.
Resolves #129 (Indiana Jones)
Resolves flickering line on Zelda 2 title screen
Resolves colored line on Micro Machines title screen
Also preliminary support for Mapper 4, submapper 3 (Acclaim's MMC3) based on Krikzz's new findings.
This is used in Mickey's Safari in Letterland and Incredible Crash Dummies
> Timing fixes

- cart.sv
- mappers/Namco.sv
Fix chr banking.
--Fixes Mindseeker
Add readback of Waveform RAM
--Fixes Namco Classic II.
Add N163 audio submapper leveling
--Simple method. Just reduces volume of APU for Submapper 4 and 5.  Needs further refinement.
> Fix Namco 163 (mapper 19)

- rtl/cart.sv
- rtl/mappers/MMC3.sv
- rtl/mappers/misc.sv
mapper 32: add WRAM support for Image fight (Japan)
mapper 88: needs hard-wired mirroring (Kitrinx)
mapper 97: missing mapper enable
> Fixes for mapper 32, 88, 97

- rtl/t65/T65.vhd
- rtl/t65/T65_MCode.vhd
Fix some undocumented opcodes to use loaded data instead of 0xEE immediate like the C64 does
> Fix some undocumented opcodes

- NES.sv
Address issue #232. Code to fix issues with old APU was creating issues with new APU :) Small pops or clicks may still be heard on loading new carts, but this is APU being initialized by new game.
> get rid of anti-pop code that was causing loud pop

- NES.sv
Add Midi option back to config string to allow use of Miracle Piano through MidiLink.
- UART31250 isn't strictly needed, just MIDI; but setting up MIDI in the menu currently requires at least one UART speed setting.
> Reenable Miracle Piano

- NES.sv
- rtl/mappers/generic.sv
- Change menu to single string in preparation for bram
- Resolve issue #250 by removing accurate size enforcement
> make menu one string, enable large mapper 28

- rtl/miracle.sv
Adding license info for the UART code copied from the Minimig project in MiSTer.
At the time of adding this code, I didn't do a thorough enough search to find this header (as it wasn't in the original [paula_uart.v]).
Having been pointed to a different file (paula.v) for the header, this is now being updated to match.
> Add header license info for UART code from Minimig

- rtl/video.sv
Reasoning:
- There are 12 color cycles.  4 for each color.
- A completely darkened color from emphasis is 3/4 of normal.
- Full darkness occurs when all 4/4 color clocks are darkened.
- A single emphasis reduction only darkens 6/12 color clocks.  This is 3 from each of the 2 darkened colors.
- So if 4/4 darkness results in 3/4 brightness, then 3/4 should be 13/16 max brightness. (aka 1/16 brightness reduction per color cycle).
> Apply emphasis bits according to cycles

- NES.sv
Reset RAM locations used by Quattro games to store game menu selections when ROM loaded.
Forces game menu selection to come up when new ROM selected.
> Force Quattro (mapper 232) menu on load

- rtl/cart.sv
- rtl/mappers/MMC3.sv
- rtl/mappers/Sachen.sv
- rtl/mappers/Sunsoft.sv
- rtl/mappers/VRC.sv
- rtl/mappers/generic.sv
- rtl/mappers/misc.sv
The following mappers now support save states:
- 30, 32, 18, 34, 65, 67, 190, 68, 72, 92, 77, 78, 70, 152, 89, 93, 184, 111, 64, 158,  75, 73, 137, 138, 139, 141, 150, 243, 136, 147, 132, 173, 172, 36, 143, 218
,
> Add savestate support for various mappers

- rtl/EEPROM_24C0x.sv
@greyrogue and @Kitrinx mentioned that the formatting was incorrect in this module regarding the `end` alignment to the `if` statements. This change fixes that and brings the formatting up to the typical methods used through most cores as well.
> Fix formatting of EEPROM_24C0x.sv

- NES.sv
- rtl/video.sv
Some menu cleanup:
-Since palettes can now be loaded, reduce the number and built-in selections to a more manageable level
-Remove boot3.rom custom palette loading in favor of FC option
-Default autosave to "on"
> Cleanup menu and palettes

- rtl/ppu.sv
Fixes issue #306 with solstice
> don't allow writes to palette ram during rendering

- rtl/cart.sv
- rtl/mappers/JYCompany.sv
- rtl/mappers/MMC2.sv
- rtl/mappers/MMC3.sv
- rtl/mappers/MMC5.sv
- rtl/mappers/VRC.sv
- rtl/mappers/misc.sv
- rtl/nes.v
- rtl/ppu.sv
This fixes the PPU to appropriately show the pattern table address as the vram address during the unused cycle 340. This is important for the MMC3 mapper to use the real inverted M2 timings as seen in the decapped chip schematics from furrtek. This fixes Wario's Woods while using the real timings. Also in this PR several of the cheat signals given to the mappers could now be removed.
> PPU Fix, Update mappers

- rtl/mappers/FDS.sv
A delay is needed for the game to handle a timer irq before starting
disk reads otherwise the timer irq will interfere with the disk irq.
> FDS: Fix SMB2J black screen on level 4-4 end

- NES.sv
- Added vmode update when the core changes video modes to ensure the HPS refreshes video timing values.
- Fixes YC values not passing for PAL / DANDY.
> Add HPS Video Mode Update

- COPYING
The copyright header for most of the files states:
```
// Copyright (c) 2012-2013 Ludvig Strigeus
// This program is GPL Licensed. See COPYING for the full license.
```
GPLv3 requires that you convey a full copy of the license, and that wasn't present in the repo, so I have added it.
> Add COPYING from FPGANES

- NES.sv
- rtl/cart.sv
- rtl/mappers/FDS.sv
- rtl/nes.v
- Moved byte_transfer_flag to $4030.d7. Tonkachi editor uses this bit to know when to read/write to $4031/$4024 instead of using interrupts.
- Adjusted prg_allow to fix instability during saving FDS to disk. prg_allow was too short during reads because of the short prg_read signal.
- Added a disk speed option for fast/original speeds. Some unlicensed games need the original speed.
> FDS: Fixes for Tonkachi, Saving instability, Speed option

- NES.sv
- rtl/nes.v
- Added option to disable video dejitter adjust video timing to meet original NES timing.  (Default is enabled)
- Note: This option only benefits those on Composite out, and may cause issues for those on HDMI or using scalars.
> Add Advanced Option to Disable Video Dejitter

- rtl/t65/T65.vhd
- rtl/t65/T65_MCode.vhd
The KIL instruction now takes infinite cycles to execute, halting the CPU until a reset occurs. Resolves #379
> Implement KIL unofficial opcode

- rtl/mappers/MMC3.sv
If the nes header specifies a size greater than the mapper allows, there must be someway to access the data. Even though the original mmc3 does not support >512KB of prg, the header is specifying a non-standard mmc3.
> Allow oversize mmc3

- NES.sv
- rtl/apu.sv
- rtl/mappers/MMC5.sv
- rtl/nes.v
- rtl/ppu.sv
This is several minor accuracy changes. Most of them are focused on edge case timings surrounding DMA and the APU line counter IRQ. There's also some bus fixes that properly isolates the behavior and selection of the APU registers and data bus that relate to the fact that on the real system the APU, DMA, and CPU were all internal to the same package.
I allowed 4 tests to keep failing:
- RNW2007 is behavior that is inconsistent between hardware revisions. It seems to mostly happen on later releases of the G revision PPUs.
- OAM corruption, arbitrary sprite 0, and OAM misalignment are all behavior surrounding the same hardware bug, and implementing that bug would require a significant refactor of the ppu code. It's best to not implement now but rather later perhaps with a full PPU refactor. …
> several accuracy fixes (passes more tests on new test rom)

- NES.sv
- rtl/mappers/MMC1.sv
- rtl/nes.v
- rtl/ppu.sv
- rtl/t65/T65.vhd
- rtl/video.sv
This fixes the following issues:
#416
#412
#375
#370
#367
#366
#364
#359
#235
#192
Additionally adds support for randomizing/clearing ram on load, borders and overscan drawing, native PPU timing signals, aligned video timing on reset to prevent video desync, support for misaligned OAM, OAM corruption, and several other isosteric behaviors of the real system. Also fixed an MMC1 bug that crashed the japanese game Shinsenden.
> Fixes several issues, major rework of the PPU
