NES.sv, nes.v
Simulates blowing into the microphone on the second controller.
=> add microphone white noise simulation

mappers/MMC5.sv
IRQs do not trigger when rendering is off. Acknowledge IRQ when starting
Vblank. Fixes Castlevania 3 intro & Mario 3 in Super Mario All-Stars.
Last CHR bank set is changed to lower banks when sprite size is changed
to 8x8 or changing banks when sprite size is 8x8. Fixes MMC5 test rom.
=> MMC5: IRQ & CHR bank fixes

ppu.sv
Just cleaning up PPU code formatting in preparation for some work. No functional changes.
=> code cleanup, no changes

NES.sv, zapper.sv
In addition to some zapper changes, this fixes a critical bug introduced around March 21 that corrupts/deletes saves. I think you should do a release after merging this.
=> zapper and saves fix

mappers/MMC5.sv
--Fixes Bandit Kings of Ancient China
=> Allow reading 0x5015 (Audio Status) in MMC5 and use CL for split screen

files.qip
Sachen mappers were not referenced in project
=> fix compile

NES.sv, video.sv
Fixes resolution reset between games in PAL mode
=> Adjust PAL vsync and video.sv last scanline

ppu.sv
Fixes glitches in Battletoads and Battletoads Double Dragon
=> PPU: Fix secondary OAM writes.

cart.sv, mappers/MMC3.sv
=> Fix DxROM (mapper 206) mirroring

ppu.sv
Allows masking of extra sprites in games that intentionally use repeat a sprite 8 times to hide additional sprites. 
Tested and working in Zelda, Castlevania II, and Gremlins.
=> allow masking of extra sprites if all 8 sprites are identical

mappers/generic.sv
This is to address issues brought up by @greyrogue 's review in #114
=> cleanup Mapper46 change

mappers/MMC3.sv
=> mapper 76 mirroring adjustment 

mappers/Sunsoft.sv
Fixes #131 Maharaja - visual glitches on boot
also tested to make sure saving works and that it is properly backed up to sd card
EDIT: paulb-nl answered my questions and this is now good to merge
=> Fix mapper 68 mirroring, add battery WRAM support

mappers/generic.sv
fixes #146
Tested with a few other mapper 30 games too, including
Battle Kid 2
Mystic Origins
Trollburner Demo
=> mapper 30: fix Twin Dragons graphical corruption

NES.sv
The Zapper trigger signal with a real NES is high for around 100ms but
with SNAC it is much shorter causing some Zappers to have compatibility
issues.
=> Option for extending SNAC Zapper trigger signal

NES.sv
To wire the second Joy.
Use same Power pin, GND and Strobe (USER_IO[0]) in Joy 2 like Joy 1
Wire clock pin of joy 2 to USER_IO[[6]
Wire data pin of joy 2 to USER_IO[3]
=> Add an option to Upgrade SNAC Protocol for control a Second Joystick to NES

mappers/generic.sv
fixes graphical glitches in Crime Busters
=> fix mapper 38 banking

rtl/ppu.sv
Fix #149 and also glitchy line in Incredible crash dummies.
=> fix startropics line

rtl/mappers/MMC3.sv
- Improves the rising lava in the "castle" level.
- Might need better implementation to fix remaining flickering.
-- See here, for alternate that uses ppu lines instead of cpu lines for timing the irq: https://forums.nesdev.com/viewtopic.php?p=241376#p241376
=> Improve Flintstones (Japan) IRQ

files.qip, rtl/mappers/MMC3.sv
also fixes missing files in files.qip
=> bring back the missing "Improve Flintstones (Japan) IRQ" commit

NES.sv, rtl/ddram.sv, rtl/nes.v, rtl/savestates.vhd
made saving savestates to sdcard default
=> fix savestates to sdcard switch behavior

rtl/mappers/generic.sv
--Fixes Alwa's Awakening demo.
=> Add PRG-RAM and oversize PRG-ROM to mapper 2

NES.sv
Reverts MiSTer-devel/NES_MiSTer#274
=> Revert "Force Quattro (mapper 232) menu on load"

rtl/cart.sv, rtl/mappers/MMC5.sv
Castlevania 3 & Uchuu Keibitai SDF
=> MMC5: Fix glitches with Extra sprites enabled

NES.sv, files.qip, rtl/keyboard.sv
'hX75: btn_up    <= pressed;
'hX72: btn_down  <= pressed;
'hX6B: btn_left  <= pressed;
'hX74: btn_right <= pressed;
'hX6C: btn_cl    <= pressed; // clr home
'hX70: btn_in    <= pressed; // ins
'hX71: btn_de    <= pressed; // del
'hX05: btn_f1    <= pressed; // 1
'hX06: btn_f2    <= pressed; // 2
'hX04: btn_f3    <= pressed; // 3
'hX0C: btn_f4    <= pressed; // 4
'hX03: btn_f5    <= pressed; // 5
'hX0B: btn_f6    <= pressed; // 6
'hX83: btn_f7    <= pressed; // 7
'hX0A: btn_f8    <= pressed; // 8
'hX16: btn_1     <= pressed; // 1
'hX1E: btn_2     <= pressed; // 2
'hX26: btn_3     <= pressed; // 3
'hX25: btn_4     <= pressed; // 4
'hX2E: btn_5     <= pressed; // 5
'hX36: btn_6     <= pressed; // 6
'hX3D: btn_7     <= pressed; // 7
'hX3E: btn_8     <= pressed; // 8
'hX46: btn_9     <= …
=> Add Keyboard support

NES.sv, rtl/apu.sv, rtl/nes.v, rtl/ppu.sv, sys/ascal.vhd, sys/sys_top.sdc, sys/sys_top.v
Apparently the reset behavior of the PPU matters for some Japanese games.
=> update sys, add toggle for PPU reset behavior
